# Site settings
title: Resume of electronic and coding projects.
description: The show case of my learned expierences through coding and building projects
# baseurl: https://epichacker16.github.io/particle//about
# url: https://epichacker16.github.io/particle/
url: https://epichacker16.github.io

# User settings
username: Reza Fakhri
user_description: I am currently a CS student at Douglas College. I am very passionate about my hobbies that include running, soldering, wood/metal work, reading and coding.	 
user_title: CS Student
email: FakhriReza@protonmail.com
twitter_username:
github_username: epichacker16
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
